[package]
name = "download_builds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10"
futures-util = "0.3.30"
log = { version = "0.4.17", features = ["kv_unstable", "kv_unstable_serde"] }
reqwest = { version = "0.11.14", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.23.0", features = ["full"] }
tracing = "0.1.40"

[dependencies.utils]
path = "../../common/utils"
