# Builds the lit node and tests and uploads as a workflow artifact
name: rust/lit-node-build
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      build_features:
        type: string
        required: true
        description: "The features to pass to the cargo build command"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG_STYLE: always
  RUST_LOG: warn,lit_node=trace,web_user_tests=trace,integration_tests=trace,ecdsa=trace,test=trace
  RUST_BACKTRACE: full
  LIT_LOGGING_SERVICE_DISABLED: 1
  LIT_CELO_DEPLOYER_PRIVATE_KEY: "0x3178746f7ae6a309d14444b4c6c85a96a4be2f53fa8950dea241d232f3e6c166"
  LIT_ALFAJORES_DEPLOYER_PRIVATE_KEY: "0x3178746f7ae6a309d14444b4c6c85a96a4be2f53fa8950dea241d232f3e6c166"
  LIT_MUMBAI_DEPLOYER_PRIVATE_KEY: "0x3178746f7ae6a309d14444b4c6c85a96a4be2f53fa8950dea241d232f3e6c166"
  LIT_POLYGON_DEPLOYER_PRIVATE_KEY: "0x3178746f7ae6a309d14444b4c6c85a96a4be2f53fa8950dea241d232f3e6c166"
  # the above are empty, do not put money in them
  IN_GITHUB_CI: 1
  LIT_LOGGING_TIMESTAMP: 1 # force adding timestamp since the CI timestamps are wrong
  CARGO_INCREMENTAL: 0

    

defaults:
  run:
    shell: bash
    working-directory: rust/lit-node

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-8x # change to LargeRunner to run on github.  Change to self-hosted to run on our own runner.  Change to buildjet-8vcpu-ubuntu-2204 to run on buildjet with 8 cpus
    timeout-minutes: 45

    steps:
      - name: Clean workspace
        working-directory: ${{ github.workspace }}
        run: |
          rm -rf ../../lit-assets
          mkdir -p ${{ github.workspace }}
      - name: Checkout lit-assets
        uses: actions/checkout@v3
      - name: Install deps
        working-directory: ${{ github.workspace }}
        run: sudo apt-get update && sudo apt-get install -y libudev-dev libsqlite3-dev cmake protobuf-compiler
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-provider: "buildjet"
          workspaces: |
            rust/lit-node
      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable # keep this up to date with rust/lit-node/rust-toolchain.toml
          components: rustfmt rust-src
      - name: Setup local files for testing
        run: make setup-local-files
      - name: Build and archive tests
        run: cargo nextest archive --archive-file nextest-archive.tar.zst --features ${{ inputs.build_features }} --test test
      - name: Upload archive to workflow
        uses: actions/upload-artifact@v4
        with:
          name: nextest-archive-${{ inputs.build_features }}
          path: rust/lit-node/nextest-archive.tar.zst